llm: openai
model: qwen/qwen3-coder
toolsets:
  - name: read_only
    tools:
      - read_file
      - read_dir
  - name: default # Special toolset that gets loaded when no other toolset is specified
    tools:
      - read_dir
      - read_file
      - write_file
      - create_dir
      - delete_file
      - delete_dir
      - execute_command

# List of additional servers (e.g., for external tools like web search)
additional_mcp_servers:

# Allowed OS commands
allowed_commands:
  - go test *
  - go fmt ./...
  - go vet *
  - go mod tidy
  - go doc *

# Filesystem access rules
filesystem_access:
  hidden:
    - "**/.git/**"
    - "secret.txt"
    - ".compell/sessions/**"
    - "bin/**"
    - work_notes.md
  read_only:
    - "go.mod"
    - "REQUIREMENTS.md"
    - "LICENSE"
    - "OBSERVATIONS.md"
